version: '3.8'

services:
  prepzo_backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: prepzo_backend_container
    ports:
      - "5001:5001"  # Map host port 5001 to container port 5001
    env_file:
      - .env        # Load environment variables from .env file
    restart: unless-stopped # Optional: Restart policy
    # Optional: Mount logs directory if you want persistent logs
    # volumes:
    #   - ./agent_logs.log:/app/agent_logs.log
    #   - ./supabase_logs.log:/app/supabase_logs.log 